2025-03-11 17:37:17.184 - RealTimeSTT: root - INFO - Starting RealTimeSTT
2025-03-11 17:37:17.248 - RealTimeSTT: root - INFO - Initializing audio recording (creating pyAudio input stream, sample rate: 16000 buffer size: 512
2025-03-11 17:37:17.256 - RealTimeSTT: root - DEBUG - Porcupine wake word detection engine initialized successfully
2025-03-11 17:37:17.256 - RealTimeSTT: root - INFO - Initializing WebRTC voice with Sensitivity 3
2025-03-11 17:37:17.256 - RealTimeSTT: root - DEBUG - WebRTC VAD voice activity detection engine initialized successfully
2025-03-11 17:37:23.080 - RealTimeSTT: torio._extension.utils - DEBUG - Loading FFmpeg6
2025-03-11 17:37:23.084 - RealTimeSTT: torio._extension.utils - DEBUG - Failed to load FFmpeg6 extension.
Traceback (most recent call last):
  File "D:\conda_env\GPTSoVits\lib\site-packages\torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "D:\conda_env\GPTSoVits\lib\site-packages\torio\_extension\utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "D:\conda_env\GPTSoVits\lib\site-packages\torio\_extension\utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "D:\conda_env\GPTSoVits\lib\site-packages\torch\_ops.py", line 1350, in load_library
    ctypes.CDLL(path)
  File "D:\conda_env\GPTSoVits\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'D:\conda_env\GPTSoVits\Lib\site-packages\torio\lib\libtorio_ffmpeg6.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
2025-03-11 17:37:23.085 - RealTimeSTT: torio._extension.utils - DEBUG - Loading FFmpeg5
2025-03-11 17:37:23.088 - RealTimeSTT: torio._extension.utils - DEBUG - Failed to load FFmpeg5 extension.
Traceback (most recent call last):
  File "D:\conda_env\GPTSoVits\lib\site-packages\torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "D:\conda_env\GPTSoVits\lib\site-packages\torio\_extension\utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "D:\conda_env\GPTSoVits\lib\site-packages\torio\_extension\utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "D:\conda_env\GPTSoVits\lib\site-packages\torch\_ops.py", line 1350, in load_library
    ctypes.CDLL(path)
  File "D:\conda_env\GPTSoVits\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'D:\conda_env\GPTSoVits\Lib\site-packages\torio\lib\libtorio_ffmpeg5.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
2025-03-11 17:37:23.089 - RealTimeSTT: torio._extension.utils - DEBUG - Loading FFmpeg4
2025-03-11 17:37:23.092 - RealTimeSTT: torio._extension.utils - DEBUG - Failed to load FFmpeg4 extension.
Traceback (most recent call last):
  File "D:\conda_env\GPTSoVits\lib\site-packages\torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "D:\conda_env\GPTSoVits\lib\site-packages\torio\_extension\utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "D:\conda_env\GPTSoVits\lib\site-packages\torio\_extension\utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "D:\conda_env\GPTSoVits\lib\site-packages\torch\_ops.py", line 1350, in load_library
    ctypes.CDLL(path)
  File "D:\conda_env\GPTSoVits\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'D:\conda_env\GPTSoVits\Lib\site-packages\torio\lib\libtorio_ffmpeg4.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
2025-03-11 17:37:23.092 - RealTimeSTT: torio._extension.utils - DEBUG - Loading FFmpeg
2025-03-11 17:37:23.093 - RealTimeSTT: torio._extension.utils - DEBUG - Failed to load FFmpeg extension.
Traceback (most recent call last):
  File "D:\conda_env\GPTSoVits\lib\site-packages\torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "D:\conda_env\GPTSoVits\lib\site-packages\torio\_extension\utils.py", line 106, in _find_versionsed_ffmpeg_extension
    raise RuntimeError(f"FFmpeg{version} extension is not available.")
RuntimeError: FFmpeg extension is not available.
2025-03-11 17:37:23.409 - RealTimeSTT: root - DEBUG - Silero VAD voice activity detection engine initialized successfully
2025-03-11 17:37:23.413 - RealTimeSTT: root - DEBUG - Starting realtime worker
2025-03-11 17:37:23.413 - RealTimeSTT: root - DEBUG - Waiting for main transcription model to start
2025-03-11 17:37:42.602 - RealTimeSTT: root - DEBUG - Main transcription model ready
2025-03-11 17:37:42.604 - RealTimeSTT: root - DEBUG - RealtimeSTT initialization completed successfully
2025-03-11 17:37:42.605 - RealTimeSTT: root - INFO - Setting listen time
2025-03-11 17:37:42.605 - RealTimeSTT: root - INFO - State changed from 'inactive' to 'listening'
2025-03-11 17:37:42.608 - RealTimeSTT: root - DEBUG - Waiting for recording start
2025-03-11 17:37:42.611 - RealTimeSTT: root - INFO - State changed from 'listening' to 'wakeword'
2025-03-11 17:37:45.422 - RealTimeSTT: root - INFO - State changed from 'wakeword' to 'listening'
2025-03-11 17:37:50.483 - RealTimeSTT: root - INFO - State changed from 'listening' to 'wakeword'
2025-03-11 17:38:23.055 - RealTimeSTT: root - INFO - KeyboardInterrupt in wait_audio, shutting down
2025-03-11 17:38:23.055 - RealTimeSTT: root - DEBUG - Finishing recording thread
2025-03-11 17:38:23.062 - RealTimeSTT: root - DEBUG - Receive from stdout pipe
2025-03-11 17:38:23.064 - RealTimeSTT: root - DEBUG - Terminating reader process
2025-03-11 17:38:23.963 - RealTimeSTT: root - DEBUG - Terminating transcription process
2025-03-11 17:38:23.983 - RealTimeSTT: root - DEBUG - Finishing realtime thread
2025-03-11 17:38:24.107 - RealTimeSTT: root - INFO - KeyboardInterrupt in text() method
2025-03-11 17:39:31.427 - RealTimeSTT: root - INFO - Starting RealTimeSTT
2025-03-11 17:39:31.454 - RealTimeSTT: root - INFO - Initializing audio recording (creating pyAudio input stream, sample rate: 16000 buffer size: 512
2025-03-11 17:39:31.459 - RealTimeSTT: root - DEBUG - Porcupine wake word detection engine initialized successfully
2025-03-11 17:39:31.459 - RealTimeSTT: root - INFO - Initializing WebRTC voice with Sensitivity 3
2025-03-11 17:39:31.459 - RealTimeSTT: root - DEBUG - WebRTC VAD voice activity detection engine initialized successfully
2025-03-11 17:39:32.478 - RealTimeSTT: torio._extension.utils - DEBUG - Loading FFmpeg6
2025-03-11 17:39:32.482 - RealTimeSTT: torio._extension.utils - DEBUG - Failed to load FFmpeg6 extension.
Traceback (most recent call last):
  File "D:\conda_env\GPTSoVits\lib\site-packages\torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "D:\conda_env\GPTSoVits\lib\site-packages\torio\_extension\utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "D:\conda_env\GPTSoVits\lib\site-packages\torio\_extension\utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "D:\conda_env\GPTSoVits\lib\site-packages\torch\_ops.py", line 1350, in load_library
    ctypes.CDLL(path)
  File "D:\conda_env\GPTSoVits\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'D:\conda_env\GPTSoVits\Lib\site-packages\torio\lib\libtorio_ffmpeg6.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
2025-03-11 17:39:32.485 - RealTimeSTT: torio._extension.utils - DEBUG - Loading FFmpeg5
2025-03-11 17:39:32.487 - RealTimeSTT: torio._extension.utils - DEBUG - Failed to load FFmpeg5 extension.
Traceback (most recent call last):
  File "D:\conda_env\GPTSoVits\lib\site-packages\torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "D:\conda_env\GPTSoVits\lib\site-packages\torio\_extension\utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "D:\conda_env\GPTSoVits\lib\site-packages\torio\_extension\utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "D:\conda_env\GPTSoVits\lib\site-packages\torch\_ops.py", line 1350, in load_library
    ctypes.CDLL(path)
  File "D:\conda_env\GPTSoVits\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'D:\conda_env\GPTSoVits\Lib\site-packages\torio\lib\libtorio_ffmpeg5.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
2025-03-11 17:39:32.488 - RealTimeSTT: torio._extension.utils - DEBUG - Loading FFmpeg4
2025-03-11 17:39:32.489 - RealTimeSTT: torio._extension.utils - DEBUG - Failed to load FFmpeg4 extension.
Traceback (most recent call last):
  File "D:\conda_env\GPTSoVits\lib\site-packages\torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "D:\conda_env\GPTSoVits\lib\site-packages\torio\_extension\utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "D:\conda_env\GPTSoVits\lib\site-packages\torio\_extension\utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "D:\conda_env\GPTSoVits\lib\site-packages\torch\_ops.py", line 1350, in load_library
    ctypes.CDLL(path)
  File "D:\conda_env\GPTSoVits\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'D:\conda_env\GPTSoVits\Lib\site-packages\torio\lib\libtorio_ffmpeg4.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
2025-03-11 17:39:32.491 - RealTimeSTT: torio._extension.utils - DEBUG - Loading FFmpeg
2025-03-11 17:39:32.491 - RealTimeSTT: torio._extension.utils - DEBUG - Failed to load FFmpeg extension.
Traceback (most recent call last):
  File "D:\conda_env\GPTSoVits\lib\site-packages\torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "D:\conda_env\GPTSoVits\lib\site-packages\torio\_extension\utils.py", line 106, in _find_versionsed_ffmpeg_extension
    raise RuntimeError(f"FFmpeg{version} extension is not available.")
RuntimeError: FFmpeg extension is not available.
2025-03-11 17:39:32.835 - RealTimeSTT: root - DEBUG - Silero VAD voice activity detection engine initialized successfully
2025-03-11 17:39:32.837 - RealTimeSTT: root - DEBUG - Starting realtime worker
2025-03-11 17:39:32.837 - RealTimeSTT: root - DEBUG - Waiting for main transcription model to start
2025-03-11 17:39:38.610 - RealTimeSTT: root - DEBUG - Main transcription model ready
2025-03-11 17:39:38.611 - RealTimeSTT: root - DEBUG - RealtimeSTT initialization completed successfully
2025-03-11 17:39:38.611 - RealTimeSTT: root - INFO - Setting listen time
2025-03-11 17:39:38.611 - RealTimeSTT: root - INFO - State changed from 'inactive' to 'listening'
2025-03-11 17:39:38.614 - RealTimeSTT: root - DEBUG - Waiting for recording start
2025-03-11 17:39:38.638 - RealTimeSTT: root - INFO - State changed from 'listening' to 'wakeword'
2025-03-11 17:40:11.435 - RealTimeSTT: root - INFO - KeyboardInterrupt in wait_audio, shutting down
2025-03-11 17:40:11.435 - RealTimeSTT: root - DEBUG - Finishing recording thread
2025-03-11 17:40:11.441 - RealTimeSTT: root - DEBUG - Terminating reader process
2025-03-11 17:40:12.257 - RealTimeSTT: root - INFO - KeyboardInterrupt in text() method
2025-03-11 17:40:19.620 - RealTimeSTT: root - INFO - Starting RealTimeSTT
2025-03-11 17:40:19.648 - RealTimeSTT: root - INFO - Initializing audio recording (creating pyAudio input stream, sample rate: 16000 buffer size: 512
2025-03-11 17:40:19.651 - RealTimeSTT: root - ERROR - Error initializing porcupine wake word detection engine: One or more keywords are not available by default. Available default keywords are:\nalexa, pico clock, grapefruit, hey google, porcupine, computer, picovoice, terminator, americano, grasshopper, jarvis, bumblebee, hey siri, ok google, blueberry
Traceback (most recent call last):
  File "D:\conda_env\GPTSoVits\lib\site-packages\RealtimeSTT\audio_recorder.py", line 684, in __init__
    self.porcupine = pvporcupine.create(
  File "D:\conda_env\GPTSoVits\lib\site-packages\pvporcupine\__init__.py", line 54, in create
    raise ValueError(
ValueError: One or more keywords are not available by default. Available default keywords are:\nalexa, pico clock, grapefruit, hey google, porcupine, computer, picovoice, terminator, americano, grasshopper, jarvis, bumblebee, hey siri, ok google, blueberry
2025-03-11 17:42:02.133 - RealTimeSTT: root - INFO - Starting RealTimeSTT
2025-03-11 17:42:02.163 - RealTimeSTT: root - INFO - Initializing audio recording (creating pyAudio input stream, sample rate: 16000 buffer size: 512
2025-03-11 17:42:02.167 - RealTimeSTT: root - ERROR - Error initializing porcupine wake word detection engine: One or more keywords are not available by default. Available default keywords are:\nhey siri, alexa, terminator, grapefruit, americano, blueberry, hey google, bumblebee, jarvis, pico clock, porcupine, computer, picovoice, grasshopper, ok google
Traceback (most recent call last):
  File "D:\conda_env\GPTSoVits\lib\site-packages\RealtimeSTT\audio_recorder.py", line 684, in __init__
    self.porcupine = pvporcupine.create(
  File "D:\conda_env\GPTSoVits\lib\site-packages\pvporcupine\__init__.py", line 54, in create
    raise ValueError(
ValueError: One or more keywords are not available by default. Available default keywords are:\nhey siri, alexa, terminator, grapefruit, americano, blueberry, hey google, bumblebee, jarvis, pico clock, porcupine, computer, picovoice, grasshopper, ok google
2025-03-11 17:42:43.524 - RealTimeSTT: root - INFO - Starting RealTimeSTT
2025-03-11 17:42:43.555 - RealTimeSTT: root - INFO - Initializing audio recording (creating pyAudio input stream, sample rate: 16000 buffer size: 512
2025-03-11 17:42:43.558 - RealTimeSTT: root - ERROR - Error initializing porcupine wake word detection engine: One or more keywords are not available by default. Available default keywords are:\ngrapefruit, picovoice, computer, americano, alexa, bumblebee, porcupine, terminator, hey google, pico clock, jarvis, hey siri, grasshopper, ok google, blueberry
Traceback (most recent call last):
  File "D:\conda_env\GPTSoVits\lib\site-packages\RealtimeSTT\audio_recorder.py", line 684, in __init__
    self.porcupine = pvporcupine.create(
  File "D:\conda_env\GPTSoVits\lib\site-packages\pvporcupine\__init__.py", line 54, in create
    raise ValueError(
ValueError: One or more keywords are not available by default. Available default keywords are:\ngrapefruit, picovoice, computer, americano, alexa, bumblebee, porcupine, terminator, hey google, pico clock, jarvis, hey siri, grasshopper, ok google, blueberry
2025-03-11 17:43:56.464 - RealTimeSTT: root - INFO - Starting RealTimeSTT
2025-03-11 17:43:56.491 - RealTimeSTT: root - INFO - Initializing audio recording (creating pyAudio input stream, sample rate: 16000 buffer size: 512
2025-03-11 17:43:56.494 - RealTimeSTT: root - ERROR - Error initializing porcupine wake word detection engine: One or more keywords are not available by default. Available default keywords are:\ncomputer, grasshopper, picovoice, hey siri, alexa, blueberry, porcupine, bumblebee, terminator, americano, hey google, grapefruit, jarvis, ok google, pico clock
Traceback (most recent call last):
  File "D:\conda_env\GPTSoVits\lib\site-packages\RealtimeSTT\audio_recorder.py", line 684, in __init__
    self.porcupine = pvporcupine.create(
  File "D:\conda_env\GPTSoVits\lib\site-packages\pvporcupine\__init__.py", line 54, in create
    raise ValueError(
ValueError: One or more keywords are not available by default. Available default keywords are:\ncomputer, grasshopper, picovoice, hey siri, alexa, blueberry, porcupine, bumblebee, terminator, americano, hey google, grapefruit, jarvis, ok google, pico clock
2025-03-11 17:44:09.746 - RealTimeSTT: root - INFO - Starting RealTimeSTT
2025-03-11 17:44:09.773 - RealTimeSTT: root - INFO - Initializing audio recording (creating pyAudio input stream, sample rate: 16000 buffer size: 512
2025-03-11 17:44:09.775 - RealTimeSTT: root - ERROR - Error initializing porcupine wake word detection engine: One or more keywords are not available by default. Available default keywords are:\ngrapefruit, grasshopper, hey google, pico clock, picovoice, ok google, bumblebee, alexa, blueberry, americano, hey siri, terminator, jarvis, computer, porcupine
Traceback (most recent call last):
  File "D:\conda_env\GPTSoVits\lib\site-packages\RealtimeSTT\audio_recorder.py", line 684, in __init__
    self.porcupine = pvporcupine.create(
  File "D:\conda_env\GPTSoVits\lib\site-packages\pvporcupine\__init__.py", line 54, in create
    raise ValueError(
ValueError: One or more keywords are not available by default. Available default keywords are:\ngrapefruit, grasshopper, hey google, pico clock, picovoice, ok google, bumblebee, alexa, blueberry, americano, hey siri, terminator, jarvis, computer, porcupine
2025-03-11 17:45:11.512 - RealTimeSTT: root - INFO - Starting RealTimeSTT
2025-03-11 17:45:11.541 - RealTimeSTT: root - INFO - Initializing audio recording (creating pyAudio input stream, sample rate: 16000 buffer size: 512
2025-03-11 17:45:11.545 - RealTimeSTT: root - ERROR - Error initializing porcupine wake word detection engine: One or more keywords are not available by default. Available default keywords are:\npicovoice, computer, alexa, hey siri, pico clock, bumblebee, jarvis, porcupine, blueberry, grapefruit, ok google, grasshopper, hey google, americano, terminator
Traceback (most recent call last):
  File "D:\conda_env\GPTSoVits\lib\site-packages\RealtimeSTT\audio_recorder.py", line 684, in __init__
    self.porcupine = pvporcupine.create(
  File "D:\conda_env\GPTSoVits\lib\site-packages\pvporcupine\__init__.py", line 54, in create
    raise ValueError(
ValueError: One or more keywords are not available by default. Available default keywords are:\npicovoice, computer, alexa, hey siri, pico clock, bumblebee, jarvis, porcupine, blueberry, grapefruit, ok google, grasshopper, hey google, americano, terminator
2025-03-11 17:46:12.085 - RealTimeSTT: root - INFO - Starting RealTimeSTT
2025-03-11 17:46:12.110 - RealTimeSTT: root - INFO - Initializing audio recording (creating pyAudio input stream, sample rate: 16000 buffer size: 512
2025-03-11 17:46:12.115 - RealTimeSTT: root - ERROR - Error initializing porcupine wake word detection engine: One or more keywords are not available by default. Available default keywords are:\nblueberry, ok google, terminator, hey siri, porcupine, jarvis, grasshopper, picovoice, bumblebee, pico clock, americano, grapefruit, hey google, alexa, computer
Traceback (most recent call last):
  File "D:\conda_env\GPTSoVits\lib\site-packages\RealtimeSTT\audio_recorder.py", line 684, in __init__
    self.porcupine = pvporcupine.create(
  File "D:\conda_env\GPTSoVits\lib\site-packages\pvporcupine\__init__.py", line 54, in create
    raise ValueError(
ValueError: One or more keywords are not available by default. Available default keywords are:\nblueberry, ok google, terminator, hey siri, porcupine, jarvis, grasshopper, picovoice, bumblebee, pico clock, americano, grapefruit, hey google, alexa, computer
2025-03-11 17:46:37.231 - RealTimeSTT: root - INFO - Starting RealTimeSTT
2025-03-11 17:46:37.260 - RealTimeSTT: root - INFO - Initializing audio recording (creating pyAudio input stream, sample rate: 16000 buffer size: 512
2025-03-11 17:46:37.264 - RealTimeSTT: root - ERROR - Error initializing porcupine wake word detection engine: One or more keywords are not available by default. Available default keywords are:\nhey siri, ok google, americano, pico clock, porcupine, computer, hey google, terminator, jarvis, blueberry, alexa, grasshopper, bumblebee, grapefruit, picovoice
Traceback (most recent call last):
  File "D:\conda_env\GPTSoVits\lib\site-packages\RealtimeSTT\audio_recorder.py", line 684, in __init__
    self.porcupine = pvporcupine.create(
  File "D:\conda_env\GPTSoVits\lib\site-packages\pvporcupine\__init__.py", line 54, in create
    raise ValueError(
ValueError: One or more keywords are not available by default. Available default keywords are:\nhey siri, ok google, americano, pico clock, porcupine, computer, hey google, terminator, jarvis, blueberry, alexa, grasshopper, bumblebee, grapefruit, picovoice
2025-03-11 17:48:35.724 - RealTimeSTT: root - INFO - Starting RealTimeSTT
2025-03-11 17:48:35.750 - RealTimeSTT: root - INFO - Initializing audio recording (creating pyAudio input stream, sample rate: 16000 buffer size: 512
2025-03-11 17:48:35.752 - RealTimeSTT: root - ERROR - Error initializing porcupine wake word detection engine: One or more keywords are not available by default. Available default keywords are:\nhey siri, hey google, terminator, pico clock, bumblebee, computer, grasshopper, jarvis, ok google, porcupine, grapefruit, blueberry, picovoice, americano, alexa
Traceback (most recent call last):
  File "D:\conda_env\GPTSoVits\lib\site-packages\RealtimeSTT\audio_recorder.py", line 684, in __init__
    self.porcupine = pvporcupine.create(
  File "D:\conda_env\GPTSoVits\lib\site-packages\pvporcupine\__init__.py", line 54, in create
    raise ValueError(
ValueError: One or more keywords are not available by default. Available default keywords are:\nhey siri, hey google, terminator, pico clock, bumblebee, computer, grasshopper, jarvis, ok google, porcupine, grapefruit, blueberry, picovoice, americano, alexa
2025-03-11 17:52:01.939 - RealTimeSTT: root - INFO - Starting RealTimeSTT
2025-03-11 17:52:01.963 - RealTimeSTT: root - INFO - Initializing audio recording (creating pyAudio input stream, sample rate: 16000 buffer size: 512
2025-03-11 17:52:01.967 - RealTimeSTT: root - INFO - Initializing WebRTC voice with Sensitivity 3
2025-03-11 17:52:01.967 - RealTimeSTT: root - DEBUG - WebRTC VAD voice activity detection engine initialized successfully
2025-03-11 17:52:03.350 - RealTimeSTT: torio._extension.utils - DEBUG - Loading FFmpeg6
2025-03-11 17:52:03.354 - RealTimeSTT: torio._extension.utils - DEBUG - Failed to load FFmpeg6 extension.
Traceback (most recent call last):
  File "D:\conda_env\GPTSoVits\lib\site-packages\torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "D:\conda_env\GPTSoVits\lib\site-packages\torio\_extension\utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "D:\conda_env\GPTSoVits\lib\site-packages\torio\_extension\utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "D:\conda_env\GPTSoVits\lib\site-packages\torch\_ops.py", line 1350, in load_library
    ctypes.CDLL(path)
  File "D:\conda_env\GPTSoVits\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'D:\conda_env\GPTSoVits\Lib\site-packages\torio\lib\libtorio_ffmpeg6.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
2025-03-11 17:52:03.356 - RealTimeSTT: torio._extension.utils - DEBUG - Loading FFmpeg5
2025-03-11 17:52:03.358 - RealTimeSTT: torio._extension.utils - DEBUG - Failed to load FFmpeg5 extension.
Traceback (most recent call last):
  File "D:\conda_env\GPTSoVits\lib\site-packages\torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "D:\conda_env\GPTSoVits\lib\site-packages\torio\_extension\utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "D:\conda_env\GPTSoVits\lib\site-packages\torio\_extension\utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "D:\conda_env\GPTSoVits\lib\site-packages\torch\_ops.py", line 1350, in load_library
    ctypes.CDLL(path)
  File "D:\conda_env\GPTSoVits\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'D:\conda_env\GPTSoVits\Lib\site-packages\torio\lib\libtorio_ffmpeg5.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
2025-03-11 17:52:03.359 - RealTimeSTT: torio._extension.utils - DEBUG - Loading FFmpeg4
2025-03-11 17:52:03.361 - RealTimeSTT: torio._extension.utils - DEBUG - Failed to load FFmpeg4 extension.
Traceback (most recent call last):
  File "D:\conda_env\GPTSoVits\lib\site-packages\torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "D:\conda_env\GPTSoVits\lib\site-packages\torio\_extension\utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "D:\conda_env\GPTSoVits\lib\site-packages\torio\_extension\utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "D:\conda_env\GPTSoVits\lib\site-packages\torch\_ops.py", line 1350, in load_library
    ctypes.CDLL(path)
  File "D:\conda_env\GPTSoVits\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'D:\conda_env\GPTSoVits\Lib\site-packages\torio\lib\libtorio_ffmpeg4.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
2025-03-11 17:52:03.362 - RealTimeSTT: torio._extension.utils - DEBUG - Loading FFmpeg
2025-03-11 17:52:03.362 - RealTimeSTT: torio._extension.utils - DEBUG - Failed to load FFmpeg extension.
Traceback (most recent call last):
  File "D:\conda_env\GPTSoVits\lib\site-packages\torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "D:\conda_env\GPTSoVits\lib\site-packages\torio\_extension\utils.py", line 106, in _find_versionsed_ffmpeg_extension
    raise RuntimeError(f"FFmpeg{version} extension is not available.")
RuntimeError: FFmpeg extension is not available.
2025-03-11 17:52:03.710 - RealTimeSTT: root - DEBUG - Silero VAD voice activity detection engine initialized successfully
2025-03-11 17:52:03.713 - RealTimeSTT: root - DEBUG - Starting realtime worker
2025-03-11 17:52:03.713 - RealTimeSTT: root - DEBUG - Waiting for main transcription model to start
2025-03-11 17:52:08.305 - RealTimeSTT: root - DEBUG - Main transcription model ready
2025-03-11 17:52:08.306 - RealTimeSTT: root - DEBUG - RealtimeSTT initialization completed successfully
2025-03-11 17:52:08.306 - RealTimeSTT: root - INFO - Setting listen time
2025-03-11 17:52:08.306 - RealTimeSTT: root - INFO - State changed from 'inactive' to 'listening'
2025-03-11 17:52:08.309 - RealTimeSTT: root - DEBUG - Waiting for recording start
2025-03-11 17:52:10.678 - RealTimeSTT: root - INFO - voice activity detected
2025-03-11 17:52:10.679 - RealTimeSTT: root - INFO - recording started
2025-03-11 17:52:10.679 - RealTimeSTT: root - INFO - State changed from 'listening' to 'recording'
2025-03-11 17:52:10.679 - RealTimeSTT: root - DEBUG - Waiting for recording stop
2025-03-11 17:52:12.089 - RealTimeSTT: root - INFO - recording stopped
2025-03-11 17:52:12.089 - RealTimeSTT: root - INFO - State changed from 'recording' to 'listening'
2025-03-11 17:52:12.089 - RealTimeSTT: root - INFO - State changed from 'listening' to 'inactive'
2025-03-11 17:52:12.131 - RealTimeSTT: root - INFO - State changed from 'inactive' to 'transcribing'
2025-03-11 17:52:12.133 - RealTimeSTT: root - DEBUG - Adding transcription request, no early transcription started
2025-03-11 17:52:12.133 - RealTimeSTT: root - DEBUG - Receive from parent_transcription_pipe after sendiung transcription request, transcribe_count: 1
2025-03-11 17:52:12.159 - RealTimeSTT: root - INFO - State changed from 'transcribing' to 'inactive'
2025-03-11 17:52:14.378 - RealTimeSTT: root - ERROR - Transcription error: Library cublas64_12.dll is not found or cannot be loaded
2025-03-11 17:52:14.379 - RealTimeSTT: root - ERROR - Error during transcription: Library cublas64_12.dll is not found or cannot be loaded
2025-03-11 17:52:52.920 - RealTimeSTT: root - INFO - voice activity detected
2025-03-11 17:52:52.920 - RealTimeSTT: root - INFO - recording started
2025-03-11 17:52:52.920 - RealTimeSTT: root - INFO - State changed from 'inactive' to 'recording'
2025-03-11 17:55:38.806 - RealTimeSTT: root - INFO - Starting RealTimeSTT
2025-03-11 17:55:38.836 - RealTimeSTT: root - INFO - Initializing audio recording (creating pyAudio input stream, sample rate: 16000 buffer size: 512
2025-03-11 17:55:38.842 - RealTimeSTT: root - INFO - Initializing WebRTC voice with Sensitivity 3
2025-03-11 17:55:38.842 - RealTimeSTT: root - DEBUG - WebRTC VAD voice activity detection engine initialized successfully
2025-03-11 17:55:39.864 - RealTimeSTT: torio._extension.utils - DEBUG - Loading FFmpeg6
2025-03-11 17:55:39.871 - RealTimeSTT: torio._extension.utils - DEBUG - Failed to load FFmpeg6 extension.
Traceback (most recent call last):
  File "D:\conda_env\GPTSoVits\lib\site-packages\torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "D:\conda_env\GPTSoVits\lib\site-packages\torio\_extension\utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "D:\conda_env\GPTSoVits\lib\site-packages\torio\_extension\utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "D:\conda_env\GPTSoVits\lib\site-packages\torch\_ops.py", line 1350, in load_library
    ctypes.CDLL(path)
  File "D:\conda_env\GPTSoVits\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'D:\conda_env\GPTSoVits\Lib\site-packages\torio\lib\libtorio_ffmpeg6.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
2025-03-11 17:55:39.874 - RealTimeSTT: torio._extension.utils - DEBUG - Loading FFmpeg5
2025-03-11 17:55:39.878 - RealTimeSTT: torio._extension.utils - DEBUG - Failed to load FFmpeg5 extension.
Traceback (most recent call last):
  File "D:\conda_env\GPTSoVits\lib\site-packages\torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "D:\conda_env\GPTSoVits\lib\site-packages\torio\_extension\utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "D:\conda_env\GPTSoVits\lib\site-packages\torio\_extension\utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "D:\conda_env\GPTSoVits\lib\site-packages\torch\_ops.py", line 1350, in load_library
    ctypes.CDLL(path)
  File "D:\conda_env\GPTSoVits\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'D:\conda_env\GPTSoVits\Lib\site-packages\torio\lib\libtorio_ffmpeg5.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
2025-03-11 17:55:39.880 - RealTimeSTT: torio._extension.utils - DEBUG - Loading FFmpeg4
2025-03-11 17:55:39.885 - RealTimeSTT: torio._extension.utils - DEBUG - Failed to load FFmpeg4 extension.
Traceback (most recent call last):
  File "D:\conda_env\GPTSoVits\lib\site-packages\torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "D:\conda_env\GPTSoVits\lib\site-packages\torio\_extension\utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "D:\conda_env\GPTSoVits\lib\site-packages\torio\_extension\utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "D:\conda_env\GPTSoVits\lib\site-packages\torch\_ops.py", line 1350, in load_library
    ctypes.CDLL(path)
  File "D:\conda_env\GPTSoVits\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'D:\conda_env\GPTSoVits\Lib\site-packages\torio\lib\libtorio_ffmpeg4.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
2025-03-11 17:55:39.887 - RealTimeSTT: torio._extension.utils - DEBUG - Loading FFmpeg
2025-03-11 17:55:39.887 - RealTimeSTT: torio._extension.utils - DEBUG - Failed to load FFmpeg extension.
Traceback (most recent call last):
  File "D:\conda_env\GPTSoVits\lib\site-packages\torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "D:\conda_env\GPTSoVits\lib\site-packages\torio\_extension\utils.py", line 106, in _find_versionsed_ffmpeg_extension
    raise RuntimeError(f"FFmpeg{version} extension is not available.")
RuntimeError: FFmpeg extension is not available.
2025-03-11 17:55:40.348 - RealTimeSTT: root - DEBUG - Silero VAD voice activity detection engine initialized successfully
2025-03-11 17:55:40.351 - RealTimeSTT: root - DEBUG - Starting realtime worker
2025-03-11 17:55:40.351 - RealTimeSTT: root - DEBUG - Waiting for main transcription model to start
2025-03-11 17:56:00.739 - RealTimeSTT: root - DEBUG - Main transcription model ready
2025-03-11 17:56:00.740 - RealTimeSTT: root - DEBUG - RealtimeSTT initialization completed successfully
2025-03-11 17:56:00.740 - RealTimeSTT: root - INFO - Setting listen time
2025-03-11 17:56:00.741 - RealTimeSTT: root - INFO - State changed from 'inactive' to 'listening'
2025-03-11 17:56:00.743 - RealTimeSTT: root - DEBUG - Waiting for recording start
2025-03-11 17:56:05.534 - RealTimeSTT: root - INFO - voice activity detected
2025-03-11 17:56:05.534 - RealTimeSTT: root - INFO - recording started
2025-03-11 17:56:05.534 - RealTimeSTT: root - INFO - State changed from 'listening' to 'recording'
2025-03-11 17:56:05.534 - RealTimeSTT: root - DEBUG - Waiting for recording stop
2025-03-11 17:56:06.814 - RealTimeSTT: root - INFO - recording stopped
2025-03-11 17:56:06.814 - RealTimeSTT: root - INFO - State changed from 'recording' to 'listening'
2025-03-11 17:56:06.814 - RealTimeSTT: root - INFO - State changed from 'listening' to 'inactive'
2025-03-11 17:56:06.871 - RealTimeSTT: root - INFO - State changed from 'inactive' to 'transcribing'
2025-03-11 17:56:06.873 - RealTimeSTT: root - DEBUG - Adding transcription request, no early transcription started
2025-03-11 17:56:06.874 - RealTimeSTT: root - INFO - State changed from 'transcribing' to 'inactive'
2025-03-11 17:56:06.878 - RealTimeSTT: root - DEBUG - Receive from parent_transcription_pipe after sendiung transcription request, transcribe_count: 1
2025-03-11 17:56:07.897 - RealTimeSTT: root - ERROR - Transcription error: Library cublas64_12.dll is not found or cannot be loaded
2025-03-11 17:56:07.897 - RealTimeSTT: root - ERROR - Error during transcription: Library cublas64_12.dll is not found or cannot be loaded
